[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true
# reduce_output = true

# Private

[tasks.boardtop_watch]
private = true
watch = { postpone = true, watch = [ "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../src/" ] }

[tasks.prepare_linux_target_on_mac]
private = true
script_runner = "@duckscript"
script = '''
# add rust toolchain
exec rustup target add x86_64-unknown-linux-gnu
# add OS compilers
exec brew tap SergioBenitez/osxct
exec brew install x86_64-unknown-linux-gnu
# setup linker for target
exec rm -rf .cargo
exec mkdir .cargo
writefile .cargo/config "[target.x86_64-unknown-linux-gnu]\nlinker = \"x86_64-unknown-linux-gnu-gcc\""
'''

[tasks.prepare_windows_target_on_mac]
private = true
script_runner = "@duckscript"
script = '''
# add rustup toolchain
exec rustup target add x86_64-pc-windows-gnu
# install mingw for compilation Windows apps
exec brew install mingw-w64
# setup linker for target
exec rm -rf .cargo
exec mkdir .cargo
writefile .cargo/config "[target.x86_64-pc-windows-gnu]\nlinker = \"x86_64-w64-mingw32-gcc\""
'''

[tasks.prepare_windows_target_on_linux]
private = true
script_runner = "@duckscript"
script = '''
# add rustup toolchain
exec rustup target add x86_64-pc-windows-gnu
# install mingw for compilation Windows apps
exec sudo apt install mingw-w64
'''

# Build from Windows to Linux and MacOs has many restrictions
# and needs many time to write some workable task

# Public

[tasks.boardtop_build]
description = "Build debug of boardtop target."
private = false
category = "Desktop"
command = "cargo"
args = [
  "build",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--bin", "boardtop"
]

[tasks.boardtop_build_release]
description = "Build release of boardtop target."
private = false
category = "Desktop"
command = "cargo"
args = [
  "build",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--bin", "boardtop",
  "--release"
]

[tasks.boardtop_build_linux_on_mac]
description = "Build boardtop target for GNU/Linux distributives on MacOS."
private = true
category = "Desktop"
dependencies = [ "prepare_linux_target_on_mac" ]
command = "cargo"
args = [
  "build",
  "--release",
  "--target", "x86_64-unknown-linux-gnu",
  "--manifest-path",
  "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--bin", "boardtop"
]

[tasks.boardtop_build_windows_on_mac]
description = "Build target for Windows on MacOS."
private = true
category = "Desktop"
dependencies = [ "prepare_windows_target_on_mac" ]
command = "cargo"
args = [
  "build",
  "--release",
  "--target", "x86_64-pc-windows-gnu",
  "--manifest-path",
  "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--bin", "boardtop"
]

[tasks.boardtop_build_windows_on_linux]
description = "Build target for Windows on Debian-based GNU/Linux disributives."
private = true
category = "Desktop"
dependencies = [ "prepare_windows_target_on_linux" ]
command = "cargo"
args = [
  "build",
  "--release",
  "--target", "x86_64-pc-windows-gnu",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--bin", "boardtop"
]

[tasks.boardtop_rebuild]
description = "Rebuild debug of boardtop target."
private = false
category = "Desktop"
command = "cargo"
args = [
  "build",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--bin", "boardtop"
]

[tasks.boardtop_run]
description = "Run debug of boardtop target"
private = false
category = "Desktop"
command = "cargo"
args = [
  "run",
  "--manifest-path", "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../../Cargo.toml",
  "--bin", "boardtop"
]

[tasks.boardtop_run_watching]
description = "Rerun debug boardtop target on file change."
category = "Desktop"
private = false
extend = "boardtop_watch"
dependencies = [ "boardtop_run" ]

