
name: Delete

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Delete older than the number of days.'
        required: true
        type: number
        default: 90

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete skipped and cancelled runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          run_conclusions: |
            cancelled
            skipped
          save_period: 0
          save_min_runs_number: 0

      - name: Delete older workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          save_period: ${{ github.event.inputs.days }}
          save_min_runs_number: 20
