
name: ForwardFromBeta

on:
  push:
    branches: [ beta ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Open Pr
        uses: vsoch/pull-request-action@1.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_TITLE: 'READY : Forward from beta to main'
          PULL_REQUEST_BODY: 'This is an automated pull request to forward changes from branch `beta` to `master`'
          PASS_IF_EXISTS: true

